apiVersion: v1
kind: ReplicationController
metadata:
 name: mysql-slave
 labels:
  name: mysql-slave
spec:
  replicas: 1
  selector:
   name: mysql-slave
  template:
   metadata:
    labels:
     name: mysql-slave
   spec:
    containers:
    - name: mysql-slave
      image: registry.cn-hangzhou.aliyuncs.com/sanchar/mysql-slave:5.7.32.0
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-slave-data
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "root"
      - name: MYSQL_MASTER_SERVICE_HOST
        value: "mysql-master"
      - name: MYSQL_REPLICATION_USER
        value: "repl"
      - name: MYSQL_REPLICATION_PASSWORD
        value: "repl"
    volumes:
     - name: mysql-slave-data
       persistentVolumeClaim:
        claimName: mysql-slave-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
   name: mysql-slave
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: http
    nodePort: 30007
  selector:
    name: mysql-slave
