apiVersion: v1
kind: ReplicationController
metadata:
 name: mysql-master
 labels:
  name: mysql-master
spec:
  replicas: 1
  selector:
   name: mysql-master
  template:
   metadata:
    labels:
     name: mysql-master
   spec:
    containers:
    - name: mysql-master
      image: registry.cn-hangzhou.aliyuncs.com/sanchar/mysql-master:5.7.32.0
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-master-data
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "root"
      - name: MYSQL_REPLICATION_USER
        value: "repl"
      - name: MYSQL_REPLICATION_PASSWORD
        value: "repl"
    volumes:
     - name: mysql-master-data
       persistentVolumeClaim:
        claimName: mysql-master-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
   name: mysql-master
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    name: http
    nodePort: 30006
  selector:
    name: mysql-master
